### ISSUE TITLE
Create a global nzem-datastore module

### ISSUE THREAD

**Issue by NigelCleland** [NigelCleland/lode#21]
Hey @djhume,

What are your thoughts regarding creating a global nzem-datastore module

Basically, there is a decent amount of different functionality and growing each day.
It could be quite good to group this all together and be able to import into different areas.

E.g. 

```
from nzemdatastore.scrapers.Scraper import Scraper
from nzemdatastore.database.NZEM import NZEM
```

This could be a cleaner way of keeping everything together?
It also sets everything up in a far nicer way to have documentation and (eventually) tests set up.

More of a traditional type style for example

**Comment by djhume** [comment]
Hi Nigel, sorry been distracted on other jobs...  
Yeap, I think this sounds great.  Sounds like it will extend its functionality and help us develop the tools as we go along. Perhaps shorten some of the names?  Not a biggy, but nzemdatastore is a bit of a mouthful!

**Comment by NigelCleland** [comment]
Me too, came down with a throat infection which really knocked me about. Just on the mend now.

Okay, some sort of pithy name which is <6-8 characters would be ideal.
Doesn't have to be related to electricity or NZ. E.g. Squirrel or something. (Because we're squirreling away data?)

Then it would simplify to

```
import squirrel as sq
sq.do_something()
```

**Comment by djhume** [comment]
Squirrel sounds good! heading away in a couple of days - looks like it's going to be a wet easter in the camper... back early May.

**Comment by djhume** [comment]
Found this on the net: perhaps use for method/class names?!

What Do Squirrels Eat?

Squirrels eat nuts, seeds, fruits, lichens, buds, mushrooms, pine cones, leaves, apples, black walnut, and bark. They especially like corn on the cob.

!!

**Comment by NigelCleland** [comment]
Oh boy, things would definitely get unreasonable if that was the case!
I'll look into names, I like ones with double meanings and get this all sorted soon.

**Comment by NigelCleland** [comment]
Hey Dave,

I went with "lode" in the end.

Few reasons, 1. Phonetically identical to Load which has electricity connotations.
2. A lode is a vein or metal, or something of value stored in the ground. Seemed fitting.
3. Very short, can be called as is, e.g.

```
import lode
from lode.scrapers.Scraper import Scraper
```
