### ISSUE TITLE
Create an abstract Scraper class and subclasses for WITS/EMI

### ISSUE THREAD

**Issue by NigelCleland** [NigelCleland/lode#7]
A lot of the core functionality of the scrapers is the same.
For example, downloading files, logging (eventually), filename parsing.
We could abstract this into a central class and then inherit from these.

**Comment by NigelCleland** [comment]
## Benefits would be
- less repeated code.
- Bug fixes propagate throughout the scrapers, not just local
- Single set of documentation
- Consistent behaviour between the scrapers

**Comment by djhume** [comment]
Agreed. A central class of repeated functions is the way to go.  Use EMIscraper for this - I think a lot of logic there can be repeated almost directly for the asx stuff.

**Comment by NigelCleland** [comment]
Started doing this 01f1ce430bddbdd4b6f31248993a70f769ed0f8f here. There are some slight differences between WITS and EMI I need to work through but I'll get this as general as I can, get EMI and WITS up and running and then look into ASX and NIWA

**Comment by NigelCleland** [comment]
This was completed but I screwed up the github commit syntax. cff3bc61388dd35c04d8344e109361559e15a2bf
